### PR TITLE
body needs to be a byte string on Python 3

### PR DESCRIPTION
**Pull request by embeddedc**
see https://www.python.org/dev/peps/pep-3333/

### CODE REVIEW

**Comment by jonashaag** [comment]
Thanks for the report and patch! Can you do it without a `six` dependency?

**Comment by embeddedc** [comment]
Better?

**Comment by jonashaag** [comment]
Yes, this is fine! If you want you can fix your Git email/GitHub username in the commit, otherwise I'll go ahead and merge this!

**Comment by embeddedc** [comment]
> If you want you can fix your Git email/GitHub username in the commit, otherwise I'll go ahead and merge this!

Sorry, copy/paste mistake => Already fixed with 93a9bf4

**Pull request merged**
